# Railway Configuration
# This file is used by Railway for deployment configuration

# Build Command
build = "pip install -r requirements.txt"

# Start Command
start = "uvicorn main:app --host 0.0.0.0 --port $PORT"

# Environment Variables (Set these in Railway Dashboard)
# DATABASE_URL = your_mysql_connection_string
# SECRET_KEY = your_jwt_secret_key
# PORT = 8000 (Railway sets this automatically)
